matrix:
  include:
    - language: ruby
      rvm:
        - 2.5.1
      services:
        - mongodb
      before_install:
        - cd server

    - language: node_js
      node_js:
        - "10"
      sudo: required
      addons:
        chrome: stable
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd client

    - language: node_js
      node_js:
        - "10"
      sudo: required
      addons:
        chrome: stable
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
        - export PATH="$HOME/.yarn/bin:$PATH"
        - cd admin-client
