production:
  clients:
    default:
      database: travel_blog
      hosts:
        - localhost:27017

development:
  clients:
    default:
      database: travel_blog_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: travel_blog_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
