# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f69a3736c24a50b933371c6ce62f6daad50b167bb10cfc8056386eb1a5b626074889b47a9ae92f3ca6f1223873ef91903db6fbb80d3d4a0b9a9f447180760f0

test:
  secret_key_base: c1862563387095a4d82595a705c75a99bf123b14c0022be07dd47bd27e94b9cdcc458dd2770d7144d208ab0da738914e9d7bf74aea6223a25853123366185136

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
